[1.1.0] Add support for MI remote unit test server
wso2/kubernetes-pipeline pull request #104
Opened 2020-09-21 19:17 UTC by ThilinaManamgoda

## Purpose
> This PR enables support for MI remote unit test server at the build stage. This fixes #95. 
## Goals
> Add support for MI remote unit test server.

## Test environment
> Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:24:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.50", GitCommit:"bc01f00cf59008a36aa47f67c37c36b9d66db718", GitTreeState:"clean", BuildDate:"2020-09-09T03:06:32Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

2020-09-21 19:40 UTC, chirangaalwis requested changes

2020-09-21 19:40 UTC, chirangaalwis commented on CHANGELOG.md
> +- Successful evaluation of Kubernetes pipeline Helm chart in Google Kubernetes Engine (GKE)
@ThilinaManamgoda let's mention the GKE Kubernetes version used.

2020-09-22 12:22 UTC, Aaquiff approved these changes

2020-09-22 12:46 UTC, chirangaalwis approved these changes

2020-09-22 12:46 UTC, merged